/* eslint-disable react/no-unknown-property */
import Head from "next/head";
import { FC, PropsWithChildren } from "react";
import CSSModules from "react-css-modules";
import Navbar from "../Navbar/Navbar";
import styles from "./Layout.module.css";

interface Props {
  children: JSX.Element | JSX.Element[];
}

const Layout: FC<Props> = ({ children }) => {
  return (
    <div styleName="container">
      <Head>
        <title>Tony Isern | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"
        />
      </Head>
      <Navbar />
      <main styleName="main">{children}</main>
    </div>
  );
};

export default CSSModules(Layout, styles, {
  allowMultiple: true,
  handleNotFoundStyleName: "log",
});
